import React, { useState } from "react";
import Head from "next/head";
import { useDataContext } from "@/context/DataContext";

export default function Home() {
  const { user, setUser } = useDataContext();

  const [name, setName] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container">
        Hola {user?.name}
        <br />
        <input type="text" placeholder="Name" onChange={(e) => setName(e.target.value)} />
        <br />
        <button onClick={() => setUser({ id: "1", name: name })}>Create User</button>
      </section>
    </>
  );
}
